project_id = "pgdfcufjdyhmaqikwbdq"

[functions.property-manifest]
verify_jwt = false

[functions.create-checkout]
verify_jwt = false

[functions.payments-webhook]
verify_jwt = false

[functions.create-portal-session]
verify_jwt = false

[functions.properties-api]
verify_jwt = false

[functions.integrations-mark-synced]
verify_jwt = false

[functions.integrations-trigger-import]
verify_jwt = true


[functions.process-email-queue]
verify_jwt = true
